name: 'Terraform'

on:
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    # Install tfenv CLI
    - name: Setup tfenv
      env:
        TFENV_URL: "https://github.com/tfutils/tfenv.git"
      run: |
        git clone "$TFENV_URL" ~/.tfenv
        echo "$HOME/.tfenv/bin" >> $GITHUB_PATH

    # Install Terraform CLI (via tfenv)
    - name: Setup Terraform
      run: |
        tfenv install

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt -check

    # Validate Terraform configuration
    - name: Terraform init & validate
      run: terraform init && terraform validate
    
    # Retrieve AWS session
    - name: Configure aws session
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/terrabits-iam-access
        role-duration-seconds: 900 # the ttl of the session, in seconds.
        aws-region: ${{ secrets.AWS_REGION }}
    
    # Plan Terraform with dummy changes
    - name: Plan Terraform with dummy values
      env:
        TF_VAR_config: "./test/dummy-values.yml"
      run: terraform plan
